### PR TITLE
Fix semver prerelease and metadata handling

### LINKED ISSUE #158: Pre-release changes still not working [Bug]
**Describe the bug**
Using the `diff-search: true` option, pre-release changes are not properly detected.

**To Reproduce**
Moving from `"version": "2.5.0-beta.0"` to `"version": "2.5.0-beta.1"` in the `package.json` file results in the following output:
```
Run EndBug/version-check@v[2](https://github.com/KeiserCorp/Keiser.A500.Display.Main/runs/6068099586?check_suite_focus=true#step:4:2)
  with:
    diff-search: true
    token: ***
    file-name: package.json
    github-api-url: https://api.github.com
Searching for version update...
Searching in 1 commit...
  Package file name: "package.json"
  Package file URL: undefined
  Version assumptions: undefined
No standard npm version commit found, switching to diff search (this could take more time...)
Checking the diffs of 1 commit...
  - 97615[4](https://github.com/KeiserCorp/Keiser.A500.Display.Main/runs/6068099586?check_suite_focus=true#step:4:4)7: added version doesn't match current one (added: "2.[5](https://github.com/KeiserCorp/Keiser.A500.Display.Main/runs/6068099586?check_suite_focus=true#step:4:5).0-beta"; current: "2.5.0-beta.1")
No matching commit found.

Outputs:
  changed: false
```

**Expected behavior**
Should result in `changed: true`.

**Additional details**
While digging for this issue I came to lines 394-396 of the `main.ts` file where I suspect the issue resides, though I don't know the output of the included package to determine if this is indeed the issue.
https://github.com/EndBug/version-check/blob/0a4902241888a3acf7fa6d959a7be7182732b0c2/src/main.ts#L394-L396

### PR DESCRIPTION
**Pull request by kusyka911**
This PR should fix #158 and related bugs.

new RegExp is based on [semver.org recommendation](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string) with minimal modifications to make it work in Node.js. Instead of using `semver-regex` from npm.

P.S. changes are not fully tested.

### CODE REVIEW

**Comment by ingLomeland** [comment]
This is a highly needed feature. How is this PR going?

**Comment by kusyka911** [comment]
> This is a highly needed feature. How is this PR going?

Feel free to use my repo, in case you also have troubles with this.
I'm going to keep it until this PR is merged. (or forever in case PR will be rejected) Also I don't have ability to test all possible scenarios. So please report any issues found in this update.

```yaml
      - name: Check if version has been updated
        id: check
        uses: kusyka911/version-check@v1.0.0-test.2
        with:
          file-url: ${{ vars.NPM_PACKAGE_JSON_URL }}
          static-checking: localIsNew
```

**Comment by EndBug** [comment]
Thank you so much for this PR ❤️ 
I'll try running some tests on your fork and then release it right away!

**Review by EndBug — APPROVED** [review]
Awesome work, really, thank you so much

@all-contributors please add @kusyka911 for their code contribution

**Comment by EndBug** [comment]
@all-contributors please add @kusyka911 for their code contribution

**Pull request merged**
