### PR TITLE
added github-api-url and change axios to got

### PR DESCRIPTION
**Pull request by JasonCubic**
I created PR so that the excellent version-check project would work in my enterprise environment.  Hopefully it helps others as well.

Changes:
- Changed axios to got.  In a heavily firewalled and proxied envionment axios gets socket hang up errors, but got works fine.
- added an optional workflow "with" value of github-api-url so that the project can be directed to an enterprise instance of github.

This change works for the enterprise instance of github at my company.

Note: your CONTRIBUTING.md file says not to include /lib/index.js but because husky forces this to be built I'm not sure how to exclude it without breaking husky?

### CODE REVIEW

**Comment by EndBug** [comment]
First of all, thank you so much for the PR!
I don't have access to GitHub Enterprise, so I'll just take you word for the fact that it works when changing the URL.
I'll just test that it works as usual and then it'll be ready to be merged!

The contributing file is outdated, thank you for letting me know, I'll fix it later 👍🏻

**Comment by JasonCubic** [comment]
That's great, thank you for reviewing.

**Comment by EndBug** [comment]
@all-contributors please add @JasonCubic for their code contribution

**Comment by EndBug** [comment]
Okay, I've published this feature in `v2.1.0` (also pointed by `v2` and `latest`). Thank you for the contribution ❤️

**Pull request merged**
